## Comment utiliser ce notebook
Cliquer sur une cellule et presser Entrée pour éditer une cellule.<br/>
Appuyer sur Shift+Entrée pour exécuter la cellule.<br/>
Pour répondre à un exercice, remplacer la ligne
```python
# <- completer ici
```
par votre code et exécuter la cellule.
<hr/>

### Recherche dans un tableau

Sous-sections :
[Vues](#vues)&nbsp;|
[Slicing](#slicing)&nbsp;|
[Copies](#copies)&nbsp;|
[Tris et filtres](#tris)&nbsp;|
[Exercices](#exercices)&nbsp;

<a id="vues"></a>
##### Vues

Il y a plusieurs moyens d'[accéder aux éléments](https://numpy.org/doc/stable/user/basics.indexing.html) d'un tableau.

In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

__Accéder à un élément__

Pour accéder à la valeur à la $3^e$ ligne, $1^{ère}$ colonne : 

In [3]:
a[2,0] # ou a[2][0] 

5

<div><img src="../images/indexation_simple.png" width="600" /></div>


De la même façon :

In [4]:
a[1]

array([3, 4])

Il faut noter que cette syntaxe permet d'accéder à une __vue__ sur le tableau, pas à une copie du tableau (si on modifie la vue, le tableau original est lui aussi modifié).

On peut aussi accéder aux éléments passant des listes d'indices pour chaque dimension :

In [5]:
a[[0,2],[1]]

array([2, 6])

<a id="slicing"></a>
##### Slicing

On utilise la même syntaxe que lorsqu'on manipule des séquences en Python pour accéder à des sous-séquences.

Par exemple, si on veut accéder aux deux premières lignes et à la première colonne :

In [6]:
a[:2,0]

array([1, 3])

<a id="copies"></a>
##### Copies

On peut demander à créer une copie du tableau avec la méthode `copy()`.

In [7]:
b = a.copy()
a[2]= np.array([[0,9]])
a,b

(array([[1, 2],
        [3, 4],
        [0, 9]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

<a id="tris"></a>
##### Tris et filtres

NumPy fournit plusieurs fonctions pour faire des [tris et recherches](https://numpy.org/doc/stable/reference/routines.sort.html#sorting) dans un tableau.

Voici quelques exemples.

__Recherche de max ou min__

La fonction `np.max` renvoie le plus grand élément du tableau qu'on lui passe comme argument
et `np.argmax` l'indice de cet élément.

In [8]:
a = np.array([[1, 2], [3, 4], [5, 0]])
a

array([[1, 2],
       [3, 4],
       [5, 0]])

In [9]:
np.max(a, axis=1)

array([2, 4, 5])

In [10]:
np.argmax(a, axis=1)

array([1, 1, 0])

__Tris__

La fonction `np.sort()` implémente des algorithmes de tri. 

In [ ]:
from cbp.similarity.measures import euclidean_sim

similarities = [euclidean_sim((0,3),xi) for xi in [(2,-5),(8,-4),(-17,-23),(28,0),(-8,-7),(3,2.9),(23,14),(7,14),(-2,28)]]
np.sort(similarities)

On peut récupérer les indices des éléments triés :

In [ ]:
np.argsort(similarities)

array([2, 3, 6, 8, 7, 4, 1, 0, 5])

__Valeurs uniques__

La fonction `np.unique()` permet d'enlever les doublons dans un tableau.

In [ ]:
y = np.array([1,0,1,0,1,1,0,0,1])
np.unique(y)

array([0, 1])

On peut récupérer les indices de chaque valeur du tableau initial dans le tableau de valeurs uniques :

In [ ]:
b = np.array([4.,8.,1.,4.,1.])
u, indices = np.unique(b,return_inverse=True)
u, indices, u[indices]

(array([1., 4., 8.]), array([1, 2, 0, 1, 0]), array([4., 8., 1., 4., 1.]))

On peut aussi récupérer le nombre de fois où chaque valeur apparaît :

In [ ]:
b = np.array([4.,8.,1.,4.,1.])
u, counts = np.unique(b,return_counts=True)
u, counts

(array([1., 4., 8.]), array([2, 2, 1]))

__Filtres__

La fonction `np.where()` permet de sélectionner les lignes d'un tableau qui satisfont certaines conditions.

In [ ]:
np.where(b<5)

(array([0, 2, 3, 4]),)

<a id="exercices"></a>
##### Exercices

__Exercice__.
Proposer une implémentation du vote majoritaire à l'aide des fonctions `np.unique` et `np.argmax`.

In [ ]:
classes_des_voisins = [1,0,1,2,1,2,0]
# <- completer ici
# vote = 

# --------- tests -------- #
try:
    assert vote ==1, 'Erreur : le nombre majoritaire dans le tableau [1,0,1,2,1,2,0] est le nombre 1.'
    print('ok')
except AssertionError as e:
    print(e)   


ok


__Exercice__. 


Le code suivant permet de calculer les similarités et de les ordonner par ordre croissant.

Remplacer l'instruction de tri dans ce code (ligne 20, fonction `tri_bulle`) par une instruction qui utilise la fonction `np.argsort`.

In [ ]:
from cbp.similarity.measures import euclidean_sim
from cbp.algo.knn import tri_bulle

X = np.array(
    [
        (2, -5),
        (8, -4),
        (-17, -23),
        (28, 0),
        (-8, -7),
        (3, 2.9),
        (23, 14),
        (7, 14),
        (-2, 28),
    ]
)
y = np.array([1, 0, 1, 0, 1, 1, 0, 0, 1])
x = np.array((0, 3))
similarites = [euclidean_sim(x, xi) for xi in X]
(_, indices) = tri_bulle(similarites)

# <- completer ici
pass

indices

array([2, 3, 6, 8, 7, 4, 1, 0, 5])