
<p style="font-size:50px">
<span style="font-size:200px">
&#9703;
</span>
 La structure de données ndarray
</p>

---



Sous-sections :
[Présentation](#presentation)&nbsp;|
[Création de tableaux](#creation)&nbsp;|
[Réorganisation de tableaux](#reorganisation)&nbsp;
[Exercices](#exercices)&nbsp;

La structure de données `ndarray` représente un tableau
multidimensionnel de nombres.

Voici par exemple un tableau multidimensionnel à 3 dimensions :

![cube](../images/cube.png)

Ce tableau est représenté par l'objet NumPy de type `ndarray` suivant :

In [ ]:
import numpy as np
a = np.array(
      [[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]]
    ).astype(np.int16)
type(a)

<a id="presentation"></a>
##### Présentation

__Stockage en interne__

Ce qui permet à NumPy de réaliser des traitements très efficaces sur ces tableaux multidimensionnels de nombres, 
c'est qu'en interne, le tableau n'est pas stocké de cette façon.
En interne, les nombres sont stockés dans des __blocs mémoire contigüs de taille fixe__.

Par exemple, un tableau de 3x3 éléments sera "aplati" pour
être stocké, puis ses éléments seront placés dans une zone contigüe de la mémoire, en
réservant un nombre fixe d’octets (ici 2) pour chaque élément :

![blocs memoire](../images/ndarray.png)

On dissocie donc la géométrie du tableau multidimensionnel (qui
comprend plusieurs dimensions)
de sa représentation en mémoire
(qui n'est faite que sur une dimension).

Un objet de type `ndarray` est 
caractérisé par une __taille fixe__
et un __même type de données__ (prédéfini à la création de l'objet)
pour tous les éléments.
Ces contraintes enlèvent un peu de flexibilité (par rapport à une liste par exemple),
mais ce sont elles qui permettent des traitements très efficaces.

__Schéma d'indexation__

Pour pouvoir accéder aux éléments du
tableau de manière transparente, comme si l'on travaillait sur un
tableau à plusieurs dimensions, 
l'implémentation du type `ndarray` associe à un bloc contigü un 
ensemble d'informations (schéma d'indexation)
sur la manière dont le tableau a été stocké en mémoire.

Celui-ci comprend :
- un *pointeur*, qui donne l'adresse mémoire du premier octet du
  tableau ;


In [ ]:
a.data

- un type de données (*data type*) commun à tous les
  éléments, comme `np.int16`, à partir duquel on peut déduire le
  nombre d'octets nécessaires pour stocker chaque élément ;


In [ ]:
a.dtype

- une géométrie (*shape*), c.-à-d., le nombre d'éléments dans
  chaque dimension, comme par exemple $(4,3,2)$ ou $(3,3)$ ;

In [ ]:
a.shape

- des pas (*stride*, déduits des deux valeurs précédentes),
  c.-à-d., le nombre d'octets à parcourir
  dans chaque dimension pour arriver à l'élément suivant ;

In [ ]:
a.strides


- un ensemble de drapeaux, qui donnent des informations sur le
  tableau (peut-il être modifié ? est-ce une vue d'un autre tableau ? etc.).

In [ ]:
a.flags

__Propriétés supplémentaires__

A partir de ces propriétés, on peut également obtenir :
- la longueur `len(a)` (nombre d'éléments sur l'axe $0$)
- le nombre total d'éléments `a.size`
- le nombre de dimensions `a.ndim`

<a id="creation"></a>
##### Création de tableaux

Il y a plusieurs manières de [créer un tableau](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation).

Voici quelques exemples.

On peut créer un tableau :
- à partir d'une liste

In [ ]:
np.array([7.61,3.])

- rempli de zéros, d'une géométrie donnée

In [ ]:
np.zeros(3)

- vide (c.-à-d. de contenu aléatoire), d'une géométrie donnée

In [ ]:
np.empty(8)

- contenant une suite de nombres successifs :

In [ ]:
np.arange(24)

- contenant un nombre donné de valeurs espacées linéairement dans un intervalle donné

In [ ]:
np.linspace(3,4,num=11)

<a id="modification"></a>
##### Modification de tableaux

A moins d'avoir que le tableau ait été figé (drapeau WRITEABLE (W)), ses éléments sont modifiables, mais pas son nombre d'éléments ou le type de ces éléments.

In [ ]:
a[0,0,1] = 87.8
a

__Réorganisation d'un tableau__

On peut néanmoins réorganiser les éléments d'un tableau pour qu'ils suivent une autre géométrie (évidemment, c'est le schéma d'indexation qui est modifié ici, pas les nombres stockés en mémoire...).

Par exemple :

In [ ]:
np.reshape(np.arange(24),(4,3,2))

__Ajout d'une dimension__

On peut aussi ajouter une dimension à un tableau,
avec la syntaxe
```python
    np.expand_dims(<array>,<position of new axis>)
```

Remarque : 
```python
    np.expand_dims(a,axis=0)
```
peut s'écrire
```python
    a[np.newaxis,:]
```
ou encore
```python
    a[None,:]
```

In [ ]:
u = np.array([3,4])
u.shape

In [ ]:
b = np.expand_dims(u,0) # ou u[np.newaxis,:] ou u[None,:]
(b, b.shape)

In [ ]:
b = np.expand_dims([3,9],1) # ou u[:,np.newaxis] ou u[:,None]
(b, b.shape)

__Concaténation de plusieurs tableaux__

On peut mettre bout à bout plusieurs tableaux à l'aide de la fonction `np.concatenate` :

In [ ]:
np.concatenate((a, np.arange(24,30).reshape((3,2))[np.newaxis,:]))

In [ ]:
u = np.array([[1, 2], [3, 4]])
v = np.array([[1], [6]])
np.concatenate((u,v),axis = 1)

Plein d'autres fonctions existent pour [manipuler des tableaux](https://numpy.org/doc/stable/reference/routines.array-manipulation.html).

<a id="exercices"></a>
##### Exercices

Voici ci-dessous une définition (avec des listes Python) de la base de cas que nous voulons utiliser.
Modifier cette définition pour que X et y soient les tableaux suivants du type `ndarray`.

```python
array([[  2. ,  -5. ],
       [  8. ,  -4. ],
       [-17. , -23. ],
       [ 28. ,   0. ],
       [ -8. ,  -7. ],
       [  3. ,   2.9],
       [ 23. ,  14. ],
       [  7. ,  14. ],
       [ -2. ,  28. ]])
array([1, 0, 1, 0, 1, 1, 0, 0, 1])
```

Quelles sont les propriétés de ces tableaux (géométrie, type de données, pas, longueur, taille, nombre de dimensions) ?

In [1]:
import numpy as np

# la base de cas (avec des listes Python)
X_list = [(2,-5),(8,-4),(-17,-23),(28,0),(-8,-7),(3,2.9),(23,14),(7,14),(-2,28)]
y_list = [1,0,1,0,1,1,0,0,1]

# a completer


A partir des tableaux X et y, comment obtenir le tableau suivant ?
```python
array([[  2. ,  -5. ,   1. ],
       [  8. ,  -4. ,   0. ],
       [-17. , -23. ,   1. ],
       [ 28. ,   0. ,   0. ],
       [ -8. ,  -7. ,   1. ],
       [  3. ,   2.9,   1. ],
       [ 23. ,  14. ,   0. ],
       [  7. ,  14. ,   0. ],
       [ -2. ,  28. ,   1. ]])
```

In [ ]:
# a completer